---
title: Nutshell Hack
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
url: 
cover: https://res.cloudinary.com/iglesk/image/upload/v1484570372/blog%20cover/Damas.jpg
avatar: https://res.cloudinary.com/iglesk/image/upload/v1484571284/blog%20cover/favicon.png
description: Nutshell Hack is A Staccato Of Random Engineering thoughts, stories and
  ideas... <br>Snowballed Into A Single blog where we hope to share our notes, journey,
  and lessons with our fellow yuppies.
bio: A lot of us are in this same boat. We Beleive nearly every problem in the world
  is already solved. It is just not written down.
reading_time: true
words_per_minute: 200
disqus_shortname: nutshell-hack
github: Nutshell-Hack
google_analytics: 
