url: /index.html
title: OSabekZ
cover: https://s3-us-west-2.amazonaws.com/caffeine-coding-bucket/2016/11coffee_background_blur_min_1457314092921-1479086063660.jpg
logo: https://caffeine-coding-bucket.s3.amazonaws.com/2016/Mar/Kelvin_min-1457599406253.jpg
description: Engineering thoughts, stories and ideas. I am a young software engineer in the Silicon Valley and I hope to share
                my notes, journey, and lessons with my fellow yuppies. 

image: 
